name: CI/CD Pipeline

# Pipeline exécuter sur toutes les branches (main, master et pull_requests)
on:
  push:
    branches:
      - main
      - master
  pull_request:

# Travail en trois étapes
jobs:
  # 1ere étape : Vérification avant le transfert
  tests:
    name: Lancement de tests + contrôle qualité + couverture
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
        
      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8
      
      - name: Analyse du code avec flake8
        run: |
          flake8 .
          
      - name: Execution des tests avec couverture
        run: |
          pytest --cov=.

  # 2eme étape : Vérification avant le transfert       
  build_and_push:
    name: Construction et Push de l'image Docker
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
  
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      
      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Construction de l'image Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/projet13_openclassroom:${{ github.sha }} .
          
      - name: Push de l'image Docker
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/projet13_openclassroom:${{ github.sha }}

  # 3eme étape : Déploiement 
  deploy:
    name: Déploiement en production
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Appel du webhook de déploiement
        run: |
          curl -X POST ${{ secrets.DEPLOY_WEBHOOK_URL }}